class ItertoolsMixin:
    iterable = None

    def accumulate(self, func=None, initial=None): ...
    def batched(self, n, strict=False): ...

    # NB: similar to concat but here only works with single iterable as param
    def chain(self, iterable): ...
    def combinations(self, r): ...
    def combinations_with_replacement(self, r): ...
    def compress(self, selectors): ...
    def count(self, start=0, step=1): ...
    def cycle(self): ...
    def dropwhile(self, predicate): ...
    def filterfalse(self, predicate): ...
    def groupby(self, key=None): ...
    def pairwise(self): ...
    def permutations(self, r=None): ...
    def product(self, repeat=1): ...
    def starmap(self, function): ...
    def takewhile(self, predicate): ...
    def tee(self, n=2): ...
    def zip_longest(self, fillvalue=None): ...
    def islice(self, stop, start=0, step=1): ...
    def repeat(self, times=None): ...

    # ### recipes ###
    # https://docs.python.org/3/library/itertools.html#itertools-recipes
    def tabulate(self, mapper, start=0): ...
    def repeat_func(self, operation, times=None): ...
    def ncycles(self, count=0): ...
    def consume(self, n=None): ...
    def take_nth(self, idx, default=None): ...
    def all_equal(self, key=None): ...
    def view(self, start=0, stop=None, step=None): ...

    # ### unique ###
    def unique(self, key=None, reverse=False): ...
    def unique_just_seen(self, key=None): ...
    def unique_ever_seen(self, key=None): ...

    # ### ###
    def sliding_window(self, n): ...
    def grouper(self, n, incomplete="fill", fill_value=None): ...
    def round_robin(self): ...
    def partition(self, predicate): ...
    def subslices(self): ...
    def find_indices(self, value, start=0, stop=None): ...

    # ### ###

    def _grouper(self, n, incomplete="fill", fill_value=None): ...
    @staticmethod
    def _unique(iterable, key=None): ...
    @staticmethod
    def _unique_ever_seen(iterable, key=None): ...
    @staticmethod
    def _sliding_window(iterable, n): ...
    @staticmethod
    def _round_robin(iterable): ...
    @staticmethod
    def _find_indices(iterable, value, start=0, stop=None): ...
