name: ci  
on:  
  push:
  pull_request:
    branches:
      - main
jobs:  
  build:  
    runs-on: ubuntu-latest  
    strategy:  
      fail-fast: false  
      matrix:  
        python-version: ["3.12"]  
    steps:  
    - uses: actions/checkout@v4  
    - name: Set up Python ${{ matrix.python-version }}  
      uses: actions/setup-python@v4  
      with:  
        python-version: ${{ matrix.python-version }} 
    - name: Install poetry
      uses: abatilo/actions-poetry@v2
    - name: Install project dependencies
      run: poetry install --with dev
    - name: Run lint
      run:  |
        poetry run ruff check --fix
        poetry run ruff format --line-length 110
    - name: Run tests
      run: poetry run pytest -v --cov=./pyrio --cov-fail-under=90 --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        directory: ./coverage/reports/
        env_vars: OS,PYTHON
        fail_ci_if_error: true
        files: ./coverage.xml,!./cache
        flags: unittests
        name: codecov-umbrella
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true
